### ISSUE TITLE
Setup Error

### ISSUE THREAD

**Issue by sibero80** [bit3725/homeassistant-mi-air-quality-monitor#1]
Hey there!
I have a Raspberry Pi 2 with HASS.io 0.65.4 installed, and followed your instructions to install this custom sensor.
This is the error output I'm getting.

Am I doing something wrong? Thank you!

```
Error while setting up platform mi_air_quality_monitor
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/miio/device.py", line 244, in send
    m = Message.parse(data, token=self.token)
  File "/usr/lib/python3.6/site-packages/construct/core.py", line 263, in parse
    return self.parse_stream(io.BytesIO(data), **contextkw)
  File "/usr/lib/python3.6/site-packages/construct/core.py", line 281, in parse_stream
    return self._parsereport(stream, context, "(parsing)")
  File "/usr/lib/python3.6/site-packages/construct/core.py", line 286, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/lib/python3.6/site-packages/construct/core.py", line 1898, in _parse
    subobj = sc._parsereport(stream, context, path)
  File "/usr/lib/python3.6/site-packages/construct/core.py", line 286, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/lib/python3.6/site-packages/construct/core.py", line 2378, in _parse
    return self.subcon._parsereport(stream, context, path)
  File "/usr/lib/python3.6/site-packages/construct/core.py", line 286, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/lib/python3.6/site-packages/construct/core.py", line 3447, in _parse
    return sc._parsereport(stream, context, path)
  File "/usr/lib/python3.6/site-packages/construct/core.py", line 286, in _parsereport
    obj = self._parse(stream, context, path)
  File "/usr/lib/python3.6/site-packages/construct/core.py", line 4548, in _parse
    hash2 if not isinstance(hash2,bytestringtype) else binascii.hexlify(hash2), ))
construct.core.ChecksumError: wrong checksum, read b'ffffffffffffffffffffffffffffffff', computed b'a3ff2a21d3ed83a7947163ae8b8693bc'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/sensor/mi_air_quality_monitor.py", line 73, in parse_data
    self._state = self._airQualityMonitor.status().aqi
  File "/usr/lib/python3.6/site-packages/miio/airqualitymonitor.py", line 67, in status
    properties
  File "/usr/lib/python3.6/site-packages/miio/device.py", line 265, in send
    "Please check your token!") from ex
miio.device.DeviceException: Got checksum error which indicates use of an invalid token. Please check your token!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 82, in async_setup
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/lib/python3.6/asyncio/futures.py", line 245, in result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/sensor/mi_air_quality_monitor.py", line 25, in setup_platform
    airQualityMonitorSensor = XiaomiAirQualityMonitorSensor(airQualityMonitor, name)
  File "/config/custom_components/sensor/mi_air_quality_monitor.py", line 40, in __init__
    self.parse_data()
  File "/config/custom_components/sensor/mi_air_quality_monitor.py", line 74, in parse_data
    except DeviceException:
NameError: name 'DeviceException' is not defined
```

**Comment by bit3725** [comment]
> miio.device.DeviceException: Got checksum error which indicates use of an invalid token. Please check your token!

Hi, saw this message in error output. I think it's because you are using a wrong device token

**Comment by sibero80** [comment]
Silly me, thank you!
